Pipelines chains together mutiple steps so that the output of each step is used as input to next step .
pipelines make it easy to apply the same preprocessing to tain and test

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
df= pd.read_csv(r"C:\Users\sus\Downloads\train.csv")

In [13]:
#Aim : train a a model so that i could predict if a member will servive or not

In [14]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [15]:
df=df.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"])

In [16]:
X_train, X_test , y_train , y_test = train_test_split(df.drop(columns=["Survived"]), df["Survived"], test_size=0.2, random_state=42)

In [17]:
X_train.head(2)

     Pclass   Sex   Age  SibSp  Parch  Fare Embarked
331       1  male  45.5      0      0  28.5        S
733       2  male  23.0      0      0  13.0        S

In [18]:
X_test.head(2)

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
709       3  male   NaN      1      1  15.2458        C
439       2  male  31.0      0      0  10.5000        S

In [19]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [20]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [21]:
#Applying imputation for missing values
si_age= SimpleImputer()# deafault strategy is mean
si_embarked= SimpleImputer(strategy="most_frequent")

X_train_age= si_age.fit_transform(X_train[["Age"]])
X_train_embarked= si_embarked.fit_transform(X_train[["Embarked"]])

X_test_age= si_age.transform(X_test[["Age"]])
X_test_embarked= si_embarked.transform(X_test[["Embarked"]])

In [22]:
# Create encoder objects

# one hot encoding Sex and Embarked

ohe_sex = OneHotEncoder(sparse_output = False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output = False,handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test_embarked)

In [25]:
X_train_sex   # we didn'tremove the fisrt column to remove multicoliniarity as we are going to 
#implement decision tree not any linear model.

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [28]:
# now we are going to concatenate the requied cols

In [29]:
X_train_rem= X_train.drop(columns=['Sex', 'Age', 'Embarked'])

In [30]:
X_test_rem = X_test.drop(columns=['Sex', 'Age', 'Embarked'])

In [31]:
X_train_transform = np.concatenate((X_train_rem , X_train_age, X_train_sex, X_train_embarked), axis=1)
X_test_transform = np.concatenate((X_test_rem , X_test_age, X_test_sex, X_test_embarked), axis=1)

In [33]:
X_train_transform.shape

(712, 10)

In [34]:
clf=DecisionTreeClassifier()
clf.fit(X_train_transform , y_train)

DecisionTreeClassifier()

In [35]:
y_pred=clf.predict(X_test_transform)

In [36]:
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1], dtype=int64)

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.776536312849162

In [38]:
import os
os.makedirs("models", exist_ok=True)

In [39]:
import pickle

In [40]:
pickle.dump(ohe_sex, open("models/ohe_sex.pkl","wb"))
pickle.dump(ohe_embarked, open("models/ohe_embarked.pkl","wb"))
pickle.dump(clf, open("models/clf.pkl","wb"))

In [ ]:
# go to pipeline2 jupyter notebook